"use client";

import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { FileText, ChevronRight } from "lucide-react";

const SECTIONS = [
  {
    id: "acceptance",
    title: "1. Acceptance of Terms",
    content: `By accessing or using AuditSmart ("the Service"), you agree to be bound by these Terms of Service ("Terms"). If you disagree with any part of these Terms, you may not access the Service.

These Terms apply to all visitors, users, and others who access or use the Service. By creating an account or using any part of our Service, you confirm that you are at least 16 years of age and have the legal capacity to enter into a binding agreement.`,
  },
  {
    id: "description",
    title: "2. Description of Service",
    content: `AuditSmart provides AI-powered smart contract security analysis ("Audits"). The Service uses multiple AI models and static analysis tools to identify potential vulnerabilities in Solidity smart contracts.

**Important Limitation:** AuditSmart is an automated analysis tool. Our Audits are not a substitute for professional human security audits, especially for high-value or production-critical contracts. We make no guarantee that our analysis will detect all vulnerabilities.

Users are solely responsible for their deployment decisions. AuditSmart assumes no liability for on-chain losses resulting from vulnerabilities not detected by our Service.`,
  },
  {
    id: "accounts",
    title: "3. User Accounts",
    content: `When you create an account, you must provide accurate and complete information. You are responsible for:

- Maintaining the confidentiality of your account credentials
- All activity that occurs under your account
- Notifying us immediately of any unauthorized use at security@auditsmart.org

We reserve the right to terminate accounts that violate these Terms, engage in fraudulent activity, or abuse the Service.`,
  },
  {
    id: "plans-billing",
    title: "4. Plans, Billing & Refunds",
    content: `**Subscription Plans:** We offer Free, Pro, and Enterprise plans as described on our Pricing page. Paid plans are billed monthly in advance.

**Free Trial:** Where offered, free trials provide full plan access for 3 days at $0. Your card is charged on day 4 unless you cancel before then.

**Cancellation:** You may cancel at any time from your Billing settings. Cancellation takes effect at the end of the current billing period. No prorated refunds are issued for partial months.

**Refund Policy:** Refunds may be granted at our discretion within 7 days of initial purchase if you have not used more than 5 audits in that billing period. Contact support@auditsmart.org.

**Pricing Changes:** We will notify you 30 days in advance of any pricing changes. Continued use after the effective date constitutes acceptance.`,
  },
  {
    id: "acceptable-use",
    title: "5. Acceptable Use Policy",
    content: `You agree not to use the Service to:

- Audit contracts intended to defraud, rug-pull, or harm other users
- Reverse-engineer, scrape, or extract our AI models or methodology
- Circumvent rate limits, audit limits, or access controls
- Attempt to exploit vulnerabilities in our platform
- Use the Service in violation of any applicable law or regulation
- Submit content that is illegal, harmful, or violates third-party rights
- Resell or sublicense access to the Service without prior written consent

We reserve the right to suspend or terminate accounts that violate this policy without notice or refund.`,
  },
  {
    id: "intellectual-property",
    title: "6. Intellectual Property",
    content: `**AuditSmart IP:** The Service, including all software, algorithms, designs, logos, and reports generated by our platform, is owned by AuditSmart and protected by copyright and intellectual property laws.

**Your Content:** You retain ownership of smart contract code you submit. By submitting code, you grant us a limited, non-exclusive license to process it for the purpose of generating your audit report. We do not store your source code (see Privacy Policy).

**Audit Reports:** Audit reports generated for your submitted contracts are provided to you for your use. You may share these reports.`,
  },
  {
    id: "disclaimers",
    title: "7. Disclaimers & Limitations of Liability",
    content: `THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.

**No Guarantee of Completeness:** We do not guarantee that our analysis will detect all vulnerabilities in your smart contract. False negatives (missed vulnerabilities) and false positives (incorrect findings) are inherent to automated analysis.

**Limitation of Liability:** TO THE MAXIMUM EXTENT PERMITTED BY LAW, AUDITSMART SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF FUNDS, DATA, OR PROFITS, ARISING FROM YOUR USE OF THE SERVICE. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT PAID BY YOU IN THE 3 MONTHS PRECEDING THE CLAIM.`,
  },
  {
    id: "indemnification",
    title: "8. Indemnification",
    content: `You agree to indemnify, defend, and hold harmless AuditSmart and its officers, directors, employees, and agents from any claims, damages, losses, liabilities, and expenses (including legal fees) arising from:

- Your use of the Service
- Your violation of these Terms
- Your violation of any third-party rights
- Any contracts you deploy to blockchain networks`,
  },
  {
    id: "governing-law",
    title: "9. Governing Law & Disputes",
    content: `These Terms are governed by the laws of Delaware, United States, without regard to conflict of law principles.

Any disputes arising from these Terms or your use of the Service shall be resolved through binding arbitration under the American Arbitration Association's Commercial Arbitration Rules. You waive the right to participate in class action lawsuits.

You may opt out of arbitration by notifying us at legal@auditsmart.org within 30 days of creating your account.`,
  },
  {
    id: "changes",
    title: "10. Changes to Terms",
    content: `We reserve the right to modify these Terms at any time. We will notify you of material changes by email or prominent notice on our platform at least 30 days before they take effect.

Your continued use of the Service after changes take effect constitutes acceptance of the new Terms. If you disagree with the changes, you must stop using the Service and may request account deletion.`,
  },
  {
    id: "contact",
    title: "11. Contact",
    content: `For questions about these Terms, contact us at:

**Email:** legal@auditsmart.org
**Mailing Address:** AuditSmart, Inc., 1234 Security Blvd, Suite 100, Wilmington, DE 19801, USA

For general inquiries visit our [Contact page](/contact).`,
  },
];

export default function TermsPage() {
  return (
    <div style={{ minHeight: "100vh", background: "var(--background)", fontFamily: "'Satoshi', sans-serif" }}>
      <Navbar />

      {/* Hero */}
      <section className="pt-28 pb-12 px-4 sm:px-6 text-center relative overflow-hidden">
        <div
          className="absolute inset-0 pointer-events-none"
          style={{
            background: "radial-gradient(ellipse 60% 40% at 50% 0%, rgba(123,47,255,0.07) 0%, transparent 70%)",
          }}
        />
        <div className="max-w-2xl mx-auto relative">
          <div
            className="w-12 h-12 rounded-xl flex items-center justify-center mx-auto mb-6"
            style={{ background: "rgba(123,47,255,0.08)", border: "1px solid rgba(123,47,255,0.18)" }}
          >
            <FileText size={22} style={{ color: "var(--brand-purple)" }} />
          </div>
          <h1
            className="text-4xl sm:text-5xl font-extrabold tracking-tight mb-4"
            style={{ color: "var(--text-primary)", letterSpacing: "-0.03em" }}
          >
            Terms of Service
          </h1>
          <p className="text-sm" style={{ color: "var(--text-muted)" }}>
            Last updated: January 1, 2025 &nbsp;·&nbsp; Effective: January 1, 2025
          </p>
          <p className="text-base mt-4 leading-relaxed" style={{ color: "var(--text-muted)" }}>
            Please read these terms carefully before using AuditSmart. They govern your use of our platform.
          </p>
        </div>
      </section>

      <div className="max-w-5xl mx-auto px-4 sm:px-6 pb-24 grid md:grid-cols-[240px_1fr] gap-10">
        {/* Sidebar TOC */}
        <aside className="hidden md:block">
          <nav className="sticky top-24 rounded-2xl p-4" style={{ background: "var(--surface-1)", border: "1px solid var(--border)" }}>
            <p className="text-[10px] font-bold uppercase tracking-widest mb-3" style={{ color: "var(--text-disabled)" }}>
              Contents
            </p>
            <ul className="space-y-1">
              {SECTIONS.map((s) => (
                <li key={s.id}>
                  <a
                    href={`#${s.id}`}
                    className="flex items-center gap-1.5 py-1.5 px-2 rounded-lg text-xs font-medium transition-all"
                    style={{ color: "var(--text-muted)" }}
                    onMouseEnter={(e) => { (e.currentTarget as HTMLElement).style.color = "var(--brand-purple)"; (e.currentTarget as HTMLElement).style.background = "rgba(123,47,255,0.06)"; }}
                    onMouseLeave={(e) => { (e.currentTarget as HTMLElement).style.color = "var(--text-muted)"; (e.currentTarget as HTMLElement).style.background = "transparent"; }}
                  >
                    <ChevronRight size={10} />
                    {s.title}
                  </a>
                </li>
              ))}
            </ul>
          </nav>
        </aside>

        {/* Content */}
        <main className="min-w-0">
          {/* Alert */}
          <div
            className="rounded-2xl p-5 mb-10"
            style={{ background: "rgba(245,158,11,0.06)", border: "1px solid rgba(245,158,11,0.2)" }}
          >
            <p className="text-sm font-semibold mb-1" style={{ color: "var(--warning)" }}>Important Notice</p>
            <p className="text-sm leading-relaxed" style={{ color: "var(--text-muted)" }}>
              AuditSmart is an automated tool. Our audits supplement but do not replace professional human security audits. Never deploy high-value contracts based solely on automated analysis.
            </p>
          </div>

          {/* Sections */}
          <div className="space-y-12">
            {SECTIONS.map((section) => (
              <section key={section.id} id={section.id} className="scroll-mt-24">
                <h2
                  className="text-xl font-bold mb-4 pb-3"
                  style={{ color: "var(--text-primary)", borderBottom: "1px solid var(--border)" }}
                >
                  {section.title}
                </h2>
                <div className="text-sm leading-relaxed" style={{ color: "var(--text-muted)" }}>
                  {section.content.split("\n\n").map((para, i) => (
                    <p key={i} className="mb-4 last:mb-0 whitespace-pre-line">
                      {para.split(/(\*\*[^*]+\*\*)/g).map((part, j) =>
                        part.startsWith("**") && part.endsWith("**")
                          ? <strong key={j} style={{ color: "var(--text-secondary)", fontWeight: 700 }}>{part.slice(2, -2)}</strong>
                          : part
                      )}
                    </p>
                  ))}
                </div>
              </section>
            ))}
          </div>
        </main>
      </div>

      <Footer />
    </div>
  );
}
