-- Add ERC specialist agent types to AgentType enum
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'ERC20_AGENT';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'ERC721_AGENT';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'ERC1155_AGENT';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'ERC4626_AGENT';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'ERC1967_AGENT';
ALTER TYPE "AgentType" ADD VALUE IF NOT EXISTS 'ERC1271_AGENT';
