import type { Metadata } from "next";
import Link from "next/link";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { ShieldCheck, AlertTriangle, Clock, CheckCircle } from "lucide-react";

export const metadata: Metadata = {
  title: "Security Policy",
  description: "AuditSmart responsible disclosure policy and security practices.",
};

const STEPS = [
  { icon: AlertTriangle, title: "Discover an issue", desc: "You find a potential security vulnerability in AuditSmart's infrastructure, code, or APIs." },
  { icon: CheckCircle, title: "Report it privately", desc: "Email security@auditsmart.org with a clear description, reproduction steps, and impact assessment." },
  { icon: Clock, title: "We respond within 48 hours", desc: "Our team will acknowledge your report and keep you updated as we investigate and resolve the issue." },
  { icon: ShieldCheck, title: "Public disclosure", desc: "We coordinate a public disclosure timeline with you once the issue is patched." },
];

export default function SecurityPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <Navbar />

      <main className="max-w-3xl mx-auto px-6 py-24">
        <div className="mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full border border-border text-xs text-muted-foreground mb-6">
            <ShieldCheck className="w-3 h-3" />
            Security
          </div>
          <h1 className="text-4xl font-bold tracking-tight mb-4">Security Policy</h1>
          <p className="text-lg text-muted-foreground">
            We take security seriously. If you&apos;ve found a vulnerability in AuditSmart, please tell us — responsibly.
          </p>
        </div>

        {/* Responsible disclosure */}
        <section className="mb-16">
          <h2 className="text-2xl font-semibold mb-8">Responsible disclosure process</h2>
          <div className="space-y-6">
            {STEPS.map(({ icon: Icon, title, desc }, i) => (
              <div key={title} className="flex gap-5">
                <div className="flex flex-col items-center">
                  <div className="p-2.5 rounded-lg bg-primary/10 border border-primary/20">
                    <Icon className="w-4 h-4 text-primary" />
                  </div>
                  {i < STEPS.length - 1 && <div className="w-px flex-1 bg-border mt-2" />}
                </div>
                <div className="pb-6">
                  <div className="font-semibold mb-1">{title}</div>
                  <div className="text-sm text-muted-foreground">{desc}</div>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Scope */}
        <section className="mb-16">
          <h2 className="text-2xl font-semibold mb-4">In scope</h2>
          <ul className="space-y-2 text-muted-foreground">
            {[
              "auditsmart.org and its subdomains",
              "API endpoints (api.auditsmart.org)",
              "Authentication and session management",
              "Payment flow security",
              "Data exposure or unauthorized access to audit reports",
            ].map((item) => (
              <li key={item} className="flex items-center gap-2">
                <CheckCircle className="w-4 h-4 text-green-500 shrink-0" />
                {item}
              </li>
            ))}
          </ul>
        </section>

        <section className="mb-16">
          <h2 className="text-2xl font-semibold mb-4">Out of scope</h2>
          <ul className="space-y-2 text-muted-foreground">
            {[
              "Denial of service attacks",
              "Social engineering of AuditSmart staff",
              "Physical security attacks",
              "Vulnerabilities in third-party services we use",
              "Reports generated by automated scanners without proof of concept",
            ].map((item) => (
              <li key={item} className="flex items-center gap-2">
                <AlertTriangle className="w-4 h-4 text-amber-500 shrink-0" />
                {item}
              </li>
            ))}
          </ul>
        </section>

        {/* CTA */}
        <div className="p-8 rounded-2xl border border-primary/20 bg-primary/5">
          <h2 className="text-xl font-semibold mb-2">Ready to report?</h2>
          <p className="text-muted-foreground mb-4">
            Send your findings to{" "}
            <a href="mailto:security@auditsmart.org" className="text-primary underline underline-offset-2">
              security@auditsmart.org
            </a>. Include a detailed description, steps to reproduce, and your assessment of the impact.
          </p>
          <p className="text-sm text-muted-foreground">
            We appreciate responsible researchers. Depending on severity, we may acknowledge your contribution publicly.
          </p>
        </div>
      </main>

      <Footer />
    </div>
  );
}
